#!/bin/sh
#
#   Copyright 2014 Jonathan M. Reid. See LICENSE.txt
#   Created by: Jon Reid, http://qualitycoding.org/
#   Source: https://github.com/jonreid/XcodeCoverage
#

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source ${DIR}/envcov.sh

remove_old_report()
{
    pushd "${BUILT_PRODUCTS_DIR}"
    if [ -e lcov ]; then
        rm -r lcov
    fi
    popd
}

create_lcov_dir()
{
    mkdir ${BUILT_PRODUCTS_DIR}/lcov
}

gather_coverage()
{
    pushd ${OBJECT_FILE_DIR_normal}/${CURRENT_ARCH}
    ${SRCROOT}/XcodeCoverage/gcovr --object-directory . --exclude '.*Platforms.*' --exclude '.*Externals.*' --exclude '.*Tests.*' --html --html-details -o ${BUILT_PRODUCTS_DIR}/lcov/coverage.html
    popd
}

generate_report()
{
    open ${BUILT_PRODUCTS_DIR}/lcov/coverage.html
}

remove_old_report
create_lcov_dir
gather_coverage
generate_report
